services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    env_file:
      - database.env
    depends_on:
      - "postgres"

  postgres:
    image:
      postgres:14.1
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - database.env

  nginx:
    image:
      nginx:1.21.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - "web"

volumes:
  postgres-data: