"""empty message

Revision ID: 04aee19878dc
Revises: 76d9b99280d2
Create Date: 2022-02-11 00:51:01.485827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04aee19878dc'
down_revision = '76d9b99280d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('position_vector_id', sa.Integer(), nullable=True))
    op.add_column('artwork', sa.Column('orientation_vector_id', sa.Integer(), nullable=True))
    op.drop_constraint('artwork_orientation_vector_fkey', 'artwork', type_='foreignkey')
    op.drop_constraint('artwork_position_vector_fkey', 'artwork', type_='foreignkey')
    op.create_foreign_key(None, 'artwork', 'vectors', ['orientation_vector_id'], ['id'])
    op.create_foreign_key(None, 'artwork', 'vectors', ['position_vector_id'], ['id'])
    op.drop_column('artwork', 'position_vector')
    op.drop_column('artwork', 'orientation_vector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('orientation_vector', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artwork', sa.Column('position_vector', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.create_foreign_key('artwork_position_vector_fkey', 'artwork', 'vectors', ['position_vector'], ['id'])
    op.create_foreign_key('artwork_orientation_vector_fkey', 'artwork', 'vectors', ['orientation_vector'], ['id'])
    op.drop_column('artwork', 'orientation_vector_id')
    op.drop_column('artwork', 'position_vector_id')
    # ### end Alembic commands ###
