"""empty message

Revision ID: 388736a66a6d
Revises: 2cc3571bdd31
Create Date: 2022-05-09 19:33:15.150069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388736a66a6d'
down_revision = '2cc3571bdd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('image_url', sa.String(length=85), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'image_url')
    # ### end Alembic commands ###
