"""empty message

Revision ID: 3f1ee566fc04
Revises: ff6c1c48c4c3
Create Date: 2022-01-12 18:56:53.945870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1ee566fc04'
down_revision = 'ff6c1c48c4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artwork_width', table_name='artwork')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_artwork_width', 'artwork', ['width'], unique=False)
    # ### end Alembic commands ###
