"""empty message

Revision ID: 51f9554c9157
Revises: 3f1ee566fc04
Create Date: 2022-01-12 19:40:43.803678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f9554c9157'
down_revision = '3f1ee566fc04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artwork', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artwork', 'images', ['image_id'], ['id'])
    op.drop_column('artwork', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('filename', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.drop_column('artwork', 'image_id')
    op.drop_table('images')
    # ### end Alembic commands ###
