"""empty message

Revision ID: 76d9b99280d2
Revises: e0134ea054c7
Create Date: 2022-02-10 23:40:08.472458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d9b99280d2'
down_revision = 'e0134ea054c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('position_vector', sa.Integer(), nullable=True))
    op.add_column('artwork', sa.Column('orientation_vector', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artwork', 'vectors', ['position_vector'], ['id'])
    op.create_foreign_key(None, 'artwork', 'vectors', ['orientation_vector'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.drop_column('artwork', 'orientation_vector')
    op.drop_column('artwork', 'position_vector')
    # ### end Alembic commands ###
