POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email":"roman.krajewski@gmx.de",
  "username": "roman",
  "name": "romankrajewski",
  "password": "hansiwursti"
}

###
POST http://localhost:5000/auth/login
Content-Type:application/json

{
  "email": "roman.krajewski@gmx.de",
  "password": "hansiwursti"
}


###
GET http://localhost:5000/api/user/roman
{
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY0MjAxMzMxNSwianRpIjoiN2YyYmRlMmQtYjVmMy00MzYxLWE0NTctZGVmZmJlMGVjYzViIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjQyMDEzMzE1LCJleHAiOjE2NDI2MTgxMTV9.6jRomE5Lb9l3fet0AapPYyGoFw4IG_DFYUNnTasmLM4
}

###
POST http://localhost:5000/api/artwork/
Content-Type: application/json

{
  "name": "Kunst3",
  "width": 10,
  "height": 10
}

###
GET http://localhost:5000/api/artwork/1

###
POST http://localhost:5000/api/image/
Content-Type: application/json

{
}