"""empty message

Revision ID: 2cc3571bdd31
Revises: 04aee19878dc
Create Date: 2022-04-13 11:31:52.361210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc3571bdd31'
down_revision = '04aee19878dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'sold')
    # ### end Alembic commands ###
