"""empty message

Revision ID: 367b8a108e46
Revises: 59116fca842a
Create Date: 2022-05-31 17:27:31.541487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367b8a108e46'
down_revision = '59116fca842a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artwork_orientation_quaternion_id_fkey', 'artwork', type_='foreignkey')
    op.create_foreign_key(None, 'artwork', 'quaternions', ['orientation_quaternion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.create_foreign_key('artwork_orientation_quaternion_id_fkey', 'artwork', 'vectors', ['orientation_quaternion_id'], ['id'])
    # ### end Alembic commands ###
