"""empty message

Revision ID: 59116fca842a
Revises: 5f742c858d78
Create Date: 2022-05-31 17:24:58.797975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59116fca842a'
down_revision = '5f742c858d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quaternions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('w', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artwork', sa.Column('orientation_quaternion_id', sa.Integer(), nullable=True))
    op.drop_constraint('artwork_orientation_vector_id_fkey', 'artwork', type_='foreignkey')
    op.create_foreign_key(None, 'artwork', 'vectors', ['orientation_quaternion_id'], ['id'])
    op.drop_column('artwork', 'orientation_vector_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('orientation_vector_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.create_foreign_key('artwork_orientation_vector_id_fkey', 'artwork', 'vectors', ['orientation_vector_id'], ['id'])
    op.drop_column('artwork', 'orientation_quaternion_id')
    op.drop_table('quaternions')
    # ### end Alembic commands ###
