"""empty message

Revision ID: 9edf98bfc923
Revises: cb6d5cb8ef44
Create Date: 2022-09-09 09:55:10.977736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9edf98bfc923'
down_revision = 'cb6d5cb8ef44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('hyperlink_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'hyperlink_url')
    # ### end Alembic commands ###
