"""empty message

Revision ID: cb6d5cb8ef44
Revises: 367b8a108e46
Create Date: 2022-08-29 18:15:38.041849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6d5cb8ef44'
down_revision = '367b8a108e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('technique', sa.String(length=100), nullable=True))
    op.add_column('artwork', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artwork', 'year')
    op.drop_column('artwork', 'technique')
    # ### end Alembic commands ###
