"""empty message

Revision ID: ff6c1c48c4c3
Revises: 2be6bee0ee53
Create Date: 2022-01-12 18:53:33.308747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff6c1c48c4c3'
down_revision = '2be6bee0ee53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('width', sa.String(length=15), nullable=True),
    sa.Column('height', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artwork_name'), 'artwork', ['name'], unique=True)
    op.create_index(op.f('ix_artwork_width'), 'artwork', ['width'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artwork_width'), table_name='artwork')
    op.drop_index(op.f('ix_artwork_name'), table_name='artwork')
    op.drop_table('artwork')
    # ### end Alembic commands ###
